import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/overlay";
import { Card, Field, Input, Switch } from "@/components/ui/primitives";
import { api } from "@/lib/api";
import { can, useAuth } from "@/lib/auth";
import { fmt, platformName } from "@/lib/utils";

type Import = {id: string; platform: string; kind: string; filename: string; status: string; summary: any};
type Preview = Import & {columns: string[]; preview: Record<string, unknown>[]};
const PLATFORMS = ["tiktok", "instagram", "youtube"].map((value) => ({value, label: platformName(value)}));
const POST_FIELDS = ["published_at", "caption", "post_id", "format", "length_seconds", "hook_style", "views", "likes", "comments", "shares", "saves", "reach", "avg_watch_time", "completion", "retention"];
const DIMENSIONS = ["countries", "cities", "ages", "genders", "active_hours"];
const label = (value: string) => ({published_at: "Post date", avg_watch_time: "Average watch time (seconds or mm:ss)", retention: "Average % watched", completion: "Completion %", length_seconds: "Length in seconds", active_hours: "When followers are active"}[value] || value.replaceAll("_", " "));

export function AnalyticsImports() {
  const orgId = useAuth((state) => state.orgId);
  const qc = useQueryClient();
  const imports = useQuery({queryKey: [orgId, "analytics-imports"], queryFn: () => api<Import[]>("/analytics/imports")});
  const summary = useQuery({queryKey: [orgId, "analytics-summary"], queryFn: () => api<any>("/analytics/summary")});
  const posts = useQuery({queryKey: [orgId, "analytics-posts"], queryFn: () => api<any[]>("/analytics/posts")});
  const presets = useQuery({queryKey: [orgId, "analytics-presets"], queryFn: () => api<any[]>("/analytics/presets")});
  const [platform, setPlatform] = useState("tiktok");
  const [kind, setKind] = useState("posts");
  const [file, setFile] = useState<File>();
  const [aggregate, setAggregate] = useState(false);
  const [preview, setPreview] = useState<Preview>();
  const [mapping, setMapping] = useState<any>({columns: {}, dimension: "countries", audience_unit: "percent", date_format: "iso", timezone: "UTC", percentage_unit: "percent", complete_distribution: false});
  const [mapped, setMapped] = useState<any>();
  const [busy, setBusy] = useState(false);
  const [manual, setManual] = useState<any>({published_at: "", caption: "", views: "", likes: "", shares: "", comments: "", completion: "", retention: "", saves: "", reach: "", avg_watch_time: "", format: "short_video"});
  const [selectedPost, setSelectedPost] = useState<string>();
  const matches = useQuery({queryKey: [orgId, "post-matches", selectedPost], queryFn: () => api<any[]>(`/analytics/posts/${selectedPost}/suggestions`), enabled: !!selectedPost});
  async function refresh() { await Promise.all(["analytics-imports", "analytics-posts", "analytics-summary", "analytics-presets", "my-audience", "calibration"].map((key) => qc.invalidateQueries({queryKey: [orgId, key]}))); }
  async function act(fn: () => Promise<unknown>) {
    setBusy(true);
    try { await fn(); await refresh(); }
    catch (e) { toast.error(e instanceof Error ? e.message : "Could not update analytics"); }
    finally { setBusy(false); }
  }
  function changeMapping(next: any) {setMapping(next); setMapped(undefined);}
  async function upload() {
    if (!file) return;
    const fd = new FormData(); fd.append("file", file); fd.append("platform", platform); fd.append("kind", kind); fd.append("aggregate_only", String(aggregate));
    await act(async () => {setPreview(await api<Preview>("/analytics/imports", {method: "POST", body: fd})); setMapped(undefined); changeMapping({...mapping, columns: {}});});
  }
  return <div className="min-w-0 space-y-5">
    {[imports.error, summary.error, posts.error, presets.error].some(Boolean) && <p role="alert" className="text-sm text-neg">Analytics could not load. Refresh this page to try again.</p>}
    <Card className="min-w-0 space-y-4 p-5"><h2 className="text-lg font-semibold">Import analytics</h2><p className="text-sm text-muted">Upload your aggregate CSV or XLSX from TikTok, Instagram or YouTube Studio. Export layouts vary: preview your file, choose its columns and save your mapping. No platform login or API key is needed.</p>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Analytics platform"><Select value={platform} onChange={setPlatform} options={PLATFORMS} /></Field><Field label="Data to import"><Select value={kind} onChange={setKind} options={[{value: "posts", label: "Post performance"}, {value: "audience", label: "Follower breakdown"}]} /></Field><Field label="Analytics file"><Input type="file" accept=".csv,.xlsx" onChange={(e) => setFile(e.target.files?.[0])} /></Field></div>
      <Switch checked={aggregate} onChange={setAggregate} label="This is my own aggregate analytics, without follower identities or individual comments" /><Button variant="primary" loading={busy} disabled={!file || !aggregate} onClick={upload}>Preview file</Button>
      {preview && <div className="space-y-4 border-t border-line pt-4"><p className="text-sm font-medium">{preview.filename} · {preview.summary.row_count} rows · {platformName(preview.platform)}</p><div className="max-w-full overflow-x-auto"><table className="dt"><thead><tr>{preview.columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{preview.preview.map((row, index) => <tr key={index}>{preview.columns.map((column) => <td className="max-w-[200px] truncate" key={column}>{String(row[column] ?? "")}</td>)}</tr>)}</tbody></table></div>
        <Field label="Reusable mapping"><Select value="" placeholder="Load a saved mapping…" onChange={(id) => {const preset = presets.data?.find((p) => p.id === id); if (preset) changeMapping(preset.mapping);}} options={(presets.data || []).filter((p) => p.platform === preview.platform && p.kind === preview.kind).map((p) => ({value: p.id, label: p.name}))} /></Field>
        {preview.kind === "audience" && <div className="grid gap-3 sm:grid-cols-2"><Field label="Breakdown"><Select value={mapping.dimension} onChange={(dimension) => changeMapping({...mapping, dimension})} options={DIMENSIONS.map((value) => ({value, label: label(value)}))} /></Field><Field label="Audience values"><Select value={mapping.audience_unit} onChange={(audience_unit) => changeMapping({...mapping, audience_unit})} options={[{value: "percent", label: "Percentages"}, {value: "count", label: "Counts"}]} /></Field><Switch checked={mapping.complete_distribution} onChange={(complete_distribution) => changeMapping({...mapping, complete_distribution})} label="This file contains the complete breakdown, not only its top categories" /></div>}
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(preview.kind === "posts" ? POST_FIELDS : ["category", "value", "dimension"]).map((field) => <Field label={label(field)} key={field}><Select value={mapping.columns[field] || "__skip__"} onChange={(value) => {const columns = {...mapping.columns}; if (value !== "__skip__") columns[field] = value; else delete columns[field]; changeMapping({...mapping, columns});}} options={[{value: "__skip__", label: "Not available / skip"}, ...preview.columns.map((value) => ({value, label: value}))]} /></Field>)}</div>
        {preview.kind === "posts" && <div className="grid gap-3 sm:grid-cols-2"><Field label="Date format"><Select value={mapping.date_format} onChange={(date_format) => changeMapping({...mapping, date_format})} options={[{value: "iso", label: "ISO: 2026-10-07"}, {value: "%d/%m/%Y", label: "Day/month/year"}, {value: "%m/%d/%Y", label: "Month/day/year"}, {value: "%b %d, %Y", label: "Oct 07, 2026"}]} /></Field><Field label="Time zone for dates without an offset"><Input value={mapping.timezone} onChange={(e) => changeMapping({...mapping, timezone: e.target.value})} placeholder="Asia/Dubai" /></Field><Field label="Completion and average % watched units"><Select value={mapping.percentage_unit} onChange={(percentage_unit) => changeMapping({...mapping, percentage_unit})} options={[{value: "percent", label: "Percent: 75 means 75%"}, {value: "fraction", label: "Fraction: 0.75 means 75%"}]} /></Field><Field label="Default post format when no column exists"><Input value={mapping.format || "unknown"} onChange={(e) => changeMapping({...mapping, format: e.target.value})} placeholder="short_video" /></Field><Field label="Analytics observation window"><Input value={mapping.reported_window || ""} onChange={(e) => changeMapping({...mapping, reported_window: e.target.value})} placeholder="e.g. first 7 days, or lifetime" /></Field></div>}
        <Field label="Category labels (optional JSON mapping)" help="For example map a country name to its two-letter code. Leave blank to keep labels as exported."><Input defaultValue="" onBlur={(e) => {try {changeMapping({...mapping, category_map: e.target.value.trim() ? JSON.parse(e.target.value) : {}});} catch {toast.error("Category mapping must be a JSON object.");}}} placeholder={'{"United Arab Emirates":"AE"}'} /></Field>
        <Field label="Save this mapping as"><Input value={mapping.preset_name || ""} onChange={(e) => changeMapping({...mapping, preset_name: e.target.value || undefined})} placeholder="Optional preset name" /></Field>
        <Button loading={busy} onClick={() => act(async () => setMapped(await api(`/analytics/imports/${preview.id}/mapping`, {method: "PUT", json: mapping})))}>Preview mapped data</Button>
        {mapped && <div className="space-y-2 rounded border border-line p-3 text-sm"><p>{mapped.summary.row_count} rows ready. Missing columns stay unavailable.</p>{mapped.summary.coverage_gaps?.map((gap: string) => <p className="text-warn" key={gap}>{gap}</p>)}{mapped.posts_preview?.map((row: any, index: number) => <p className="break-words" key={index}>{row.caption || "Untitled"} · {row.published_at} · {Object.entries(row.metrics).map(([key, value]) => `${label(key)}: ${value}`).join(" · ")}</p>)}<Button variant="primary" loading={busy} onClick={() => act(async () => {await api(`/analytics/imports/${preview.id}/apply`, {method: "POST"}); setPreview(undefined); setMapped(undefined); toast.success("Analytics imported. Available audience breakdowns are ready to match.");})}>Import mapped data</Button></div>}
      </div>}
      <details className="border-t border-line pt-3"><summary className="cursor-pointer text-sm font-medium">Enter a post manually</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Post date"><Input type="datetime-local" value={manual.published_at} onChange={(e) => setManual({...manual, published_at: e.target.value})} /></Field><Field label="Post format"><Select value={manual.format} onChange={(format) => setManual({...manual, format})} options={["short_video", "video", "image", "carousel", "text", "audio"].map((value) => ({value, label: label(value)}))} /></Field><Field label="Caption or title"><Input value={manual.caption} onChange={(e) => setManual({...manual, caption: e.target.value})} /></Field>{["views", "likes", "shares", "comments", "saves", "reach", "avg_watch_time", "completion", "retention"].map((key) => <Field label={label(key)} key={key}><Input type="number" min={0} value={manual[key]} onChange={(e) => setManual({...manual, [key]: e.target.value})} /></Field>)}<Button loading={busy} disabled={!manual.published_at || !aggregate} onClick={() => act(async () => {await api("/analytics/manual", {json: {platform, published_at: new Date(manual.published_at).toISOString(), caption: manual.caption, format: manual.format, metrics: Object.fromEntries(Object.entries(manual).filter(([key, value]) => !["published_at", "caption", "format"].includes(key) && value !== "").map(([key, value]) => [key, Number(value)])), aggregate_only: true}}); toast.success("Post recorded");})}>Save post analytics</Button></div></details>
    </Card>
    <div className="grid gap-5 lg:grid-cols-2"><Card className="space-y-3 p-5"><h2 className="font-semibold">Your usual results</h2>{Object.entries(summary.data?.platforms || {}).map(([platform, value]: any) => <div key={platform}><h3 className="text-sm font-medium">{platformName(platform)} · {value.n} posts</h3><p className="mt-1 text-sm text-muted">{Object.entries(value.medians).map(([key, number]) => `${label(key)}: ${typeof number === "number" ? fmt.n(number) : number}`).join(" · ")}</p></div>)}{!summary.data?.baseline?.n && <p className="text-sm text-muted">Import post performance to calculate your own medians.</p>}<p className="text-xs text-muted">{summary.data?.method}</p></Card>
      <Card className="space-y-3 p-5"><h2 className="font-semibold">What works for you</h2>{summary.data?.patterns?.map((pattern: any) => <p className="text-sm" key={`${pattern.dimension}:${pattern.value}`}>{label(pattern.dimension)}: <strong>{pattern.value}</strong> · {pattern.n} of your best posts · {fmt.n(pattern.median_views)} median views</p>)}{!summary.data?.patterns?.length && <p className="text-sm text-muted">Map formats, lengths, hook styles and posting times to see patterns in your own best posts. We do not guess missing metadata.</p>}</Card></div>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">Link published posts to tests</h2><p className="text-sm text-muted">Suggestions use the date and caption. Confirm the right test; linked outcomes appear in <Link className="text-brand" to="/calibration">Calibration</Link>. Only predictions made before publication count towards accuracy estimates.</p>{posts.data?.map((post) => <div className="flex min-w-0 flex-wrap items-center gap-3 border-t border-line pt-3 text-sm" key={post.id}><span className="min-w-0 flex-1 break-words">{post.caption.slice(0, 120) || "Untitled post"} · {platformName(post.platform)} · {fmt.day(post.published_at)}</span>{post.simulation_id ? <><Link className="text-brand" to={`/simulations/${post.simulation_id}`}>Linked test</Link><Button size="sm" onClick={() => act(() => api(`/analytics/posts/${post.id}/link`, {method: "PUT", json: {simulation_id: null}}))}>Unlink</Button></> : <Button size="sm" onClick={() => setSelectedPost(post.id)}>Find a matching test</Button>}{selectedPost === post.id && <div className="basis-full space-y-2">{matches.data?.map((match) => <div className="flex flex-wrap items-center gap-2" key={match.simulation_id}><span>{match.name} · {match.days_apart} days apart</span><Button size="sm" loading={busy} onClick={() => act(async () => {await api(`/analytics/posts/${post.id}/link`, {method: "PUT", json: {simulation_id: match.simulation_id}}); setSelectedPost(undefined);})}>Link this test</Button>{match.has_variant_b && <Button size="sm" loading={busy} onClick={() => act(async () => {await api(`/analytics/posts/${post.id}/link`, {method: "PUT", json: {simulation_id: match.simulation_id, variant: "B"}}); setSelectedPost(undefined);})}>Link variant B</Button>}</div>)}{matches.data?.length === 0 && <p>No completed tests on this platform yet.</p>}</div>}</div>)}</Card>
    <Card className="space-y-3 p-5"><h2 className="font-semibold">Imported files</h2>{imports.data?.map((row) => <p className="break-words text-sm" key={row.id}>{row.filename} · {platformName(row.platform)} · {row.kind} · {row.status} · {row.summary.row_count} rows</p>)}{imports.data?.filter((row) => row.status === "applied" && row.kind === "audience").map((row) => <div className="break-words text-sm" key={`audience:${row.id}`}>{Object.entries(row.summary.audience || {}).map(([dimension, categories]: any) => <p key={dimension}>{label(dimension)}: {Object.entries(categories).map(([category, value]) => `${category}: ${value}${row.summary.unit === "percent" ? "%" : " followers"}`).join(" · ")}</p>)}{row.summary.coverage_gaps?.map((gap: string) => <p className="text-warn" key={gap}>{gap}</p>)}</div>)}<p className="text-xs text-muted">Files, rows and mappings stay in this workspace. Imported data is never included in the public accuracy programme.</p>{can("admin") && <Button variant="danger" loading={busy} onClick={() => {if (confirm("Delete all imported files, post analytics, saved import mappings and their calibration links in this workspace? Your tests and manually entered audience definitions remain.")) act(async () => {await api("/analytics/delete", {json: {confirmed: true}}); setPreview(undefined); setMapped(undefined); toast.success("Imported data deleted");});}}>Delete imported data</Button>}</Card>
  </div>;
}
