"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01 19:09:17.830654
"""
import sqlalchemy as sa
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=120), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('population_versions',
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('priors', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('dataset_ids', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_population_versions'))
    )
    with op.batch_alter_table('population_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_versions_created_at'), ['created_at'], unique=False)

    op.create_table('region_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('brief_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_region_snapshots'))
    )
    with op.batch_alter_table('region_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_region_snapshots_region_hour', ['region', 'hour'], unique=True)

    op.create_table('signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_region_time', ['region', 'observed_at'], unique=False)
        batch_op.create_index('ix_signals_source_time', ['source', 'fetched_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_api_keys_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)

    op.create_table('connectors',
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('secrets_enc', sa.Text(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_items', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_connectors_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors'))
    )
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connectors_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_connectors_org_key', ['org_id', 'key'], unique=True)

    op.create_table('credit_ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_credit_ledger_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger'))
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('datasets',
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('columns', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('preview', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('mapping', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_datasets_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_org_id'), ['org_id'], unique=False)

    op.create_table('invites',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invites_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_invites_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invites_token_hash'))
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invites_org_id'), ['org_id'], unique=False)

    op.create_table('memberships',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_memberships_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_projects_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_org_id'), ['org_id'], unique=False)

    op.create_table('provider_configs',
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_enc', sa.String(length=2000), nullable=True),
    sa.Column('voice_model', sa.String(length=200), nullable=False),
    sa.Column('report_model', sa.String(length=200), nullable=False),
    sa.Column('vision_model', sa.String(length=200), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('json_mode', sa.Boolean(), nullable=False),
    sa.Column('price_in', sa.Float(), nullable=True),
    sa.Column('price_cached', sa.Float(), nullable=True),
    sa.Column('price_out', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_provider_configs_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_configs'))
    )
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_configs_org_id'), ['org_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_usage_events_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index('ix_usage_org_time', ['org_id', 'created_at'], unique=False)

    op.create_table('assets',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('text_excerpt', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_assets_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_assets_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)

    op.create_table('simulations',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('content', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('audience', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ontology', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('card', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('usage', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('credits_estimate', sa.Integer(), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('report_status', sa.String(length=24), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_simulations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_simulations_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_simulations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulations'))
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_status'), ['status'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('sim_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.String(length=12), nullable=False),
    sa.Column('actor_ref', sa.String(length=64), nullable=False),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('target_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('target_ref', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_actions_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index('ix_actions_sim_round', ['simulation_id', 'round'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_chat_messages_simulation_id_simulations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_sim_target', ['simulation_id', 'target'], unique=False)

    op.create_table('graph_edges',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('src', sa.String(length=160), nullable=False),
    sa.Column('dst', sa.String(length=160), nullable=False),
    sa.Column('relation', sa.String(length=80), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_graph_edges_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges'))
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_graph_nodes_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_nodes'))
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_graph_nodes_sim_key', ['simulation_id', 'key'], unique=True)
        batch_op.create_index(batch_op.f('ix_graph_nodes_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('performance_reports',
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('retention', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_performance_reports_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_performance_reports_reported_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_performance_reports_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_reports'))
    )
    with op.batch_alter_table('performance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_reports_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_reports_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('author_ref', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('root_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('variant', sa.String(length=2), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('sim_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('source_url', sa.String(length=800), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_posts_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('reports',
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('outline', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_reports_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('sim_agents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('persona', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('reaction', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('state', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_sim_agents_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sim_agents'))
    )
    with op.batch_alter_table('sim_agents', schema=None) as batch_op:
        batch_op.create_index('ix_sim_agents_sim_ref', ['simulation_id', 'ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_sim_agents_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('sim_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_sim_events_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sim_events'))
    )
    with op.batch_alter_table('sim_events', schema=None) as batch_op:
        batch_op.create_index('ix_sim_events_sim_seq', ['simulation_id', 'seq'], unique=True)

    op.create_table('surveys',
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('answers', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_surveys_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_surveys'))
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_surveys_simulation_id'), ['simulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_surveys_created_at'))

    op.drop_table('surveys')
    with op.batch_alter_table('sim_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sim_events_sim_seq')

    op.drop_table('sim_events')
    with op.batch_alter_table('sim_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sim_agents_simulation_id'))
        batch_op.drop_index('ix_sim_agents_sim_ref')

    op.drop_table('sim_agents')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_simulation_id'))

    op.drop_table('posts')
    with op.batch_alter_table('performance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_reports_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_performance_reports_org_id'))
        batch_op.drop_index(batch_op.f('ix_performance_reports_created_at'))

    op.drop_table('performance_reports')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_simulation_id'))
        batch_op.drop_index('ix_graph_nodes_sim_key')

    op.drop_table('graph_nodes')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_simulation_id'))

    op.drop_table('graph_edges')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_sim_target')

    op.drop_table('chat_messages')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_sim_round')

    op.drop_table('actions')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_status'))
        batch_op.drop_index(batch_op.f('ix_simulations_project_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_org_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_created_at'))

    op.drop_table('simulations')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_assets_org_id'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))

    op.drop_table('assets')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_org_time')

    op.drop_table('usage_events')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_configs_org_id'))
        batch_op.drop_index(batch_op.f('ix_provider_configs_created_at'))

    op.drop_table('provider_configs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_org_id'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_org_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_created_at'))

    op.drop_table('memberships')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_org_id'))
        batch_op.drop_index(batch_op.f('ix_invites_email'))
        batch_op.drop_index(batch_op.f('ix_invites_created_at'))

    op.drop_table('invites')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_org_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_created_at'))

    op.drop_table('datasets')
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_org_time')

    op.drop_table('credit_ledger')
    with op.batch_alter_table('connectors', schema=None) as batch_op:
        batch_op.drop_index('ix_connectors_org_key')
        batch_op.drop_index(batch_op.f('ix_connectors_created_at'))

    op.drop_table('connectors')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_created_at'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_source_time')
        batch_op.drop_index('ix_signals_region_time')

    op.drop_table('signals')
    with op.batch_alter_table('region_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_region_snapshots_region_hour')

    op.drop_table('region_snapshots')
    with op.batch_alter_table('population_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_population_versions_created_at'))

    op.drop_table('population_versions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_created_at'))

    op.drop_table('organizations')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_time')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
