"""creator analytics audience and automatic calibration

Revision ID: 6fbee1b10c17
Revises: 20261002_0003
Create Date: 2026-10-03 19:45:49.381097
"""
import sqlalchemy as sa
from alembic import op

revision = '6fbee1b10c17'
down_revision = '20261002_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_connections',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=24), nullable=False),
    sa.Column('account_id', sa.String(length=200), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('tokens_enc', sa.Text(), nullable=True),
    sa.Column('state_hash', sa.String(length=64), nullable=True),
    sa.Column('state_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audience', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('share_accuracy', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_social_connections_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_connections'))
    )
    with op.batch_alter_table('social_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_connections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_connections_next_sync_at'), ['next_sync_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_connections_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_connections_state_hash'), ['state_hash'], unique=False)
        batch_op.create_index('uq_social_connections_org_platform', ['org_id', 'platform'], unique=True)

    op.create_table('social_posts',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=1), nullable=False),
    sa.Column('post_id', sa.String(length=200), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=False),
    sa.Column('prediction', sa.JSON(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['social_connections.id'], name=op.f('fk_social_posts_connection_id_social_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_social_posts_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_social_posts_simulation_id_simulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_posts'))
    )
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_posts_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_posts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_posts_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index('uq_social_post_account_post', ['connection_id', 'post_id'], unique=True)
        batch_op.create_index('uq_social_post_variant', ['org_id', 'simulation_id', 'variant'], unique=True)

    with op.batch_alter_table('performance_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant', sa.String(length=1), server_default='A', nullable=False))
        batch_op.add_column(sa.Column('social_post_id', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_performance_reports_social_post_id'), ['social_post_id'])
        batch_op.create_foreign_key(batch_op.f('fk_performance_reports_social_post_id_social_posts'), 'social_posts', ['social_post_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performance_reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_performance_reports_social_post_id_social_posts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_performance_reports_social_post_id'), type_='unique')
        batch_op.drop_column('social_post_id')
        batch_op.drop_column('variant')

    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_index('uq_social_post_variant')
        batch_op.drop_index('uq_social_post_account_post')
        batch_op.drop_index(batch_op.f('ix_social_posts_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_social_posts_org_id'))
        batch_op.drop_index(batch_op.f('ix_social_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_social_posts_connection_id'))

    op.drop_table('social_posts')
    with op.batch_alter_table('social_connections', schema=None) as batch_op:
        batch_op.drop_index('uq_social_connections_org_platform')
        batch_op.drop_index(batch_op.f('ix_social_connections_state_hash'))
        batch_op.drop_index(batch_op.f('ix_social_connections_org_id'))
        batch_op.drop_index(batch_op.f('ix_social_connections_next_sync_at'))
        batch_op.drop_index(batch_op.f('ix_social_connections_created_at'))

    op.drop_table('social_connections')
    # ### end Alembic commands ###
