"""Collaboration (annotations, review status), audience templates (persona library), version history and benchmark fields.

Revision ID: 20261002_0002
Revises: 0001
Create Date: 2026-10-01 20:47:38.085378
"""
import sqlalchemy as sa
from alembic import op

revision = '20261002_0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_templates',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_audience_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audience_templates_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_templates'))
    )
    with op.batch_alter_table('audience_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audience_templates_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_templates_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audience_templates_shared'), ['shared'], unique=False)

    op.create_table('annotations',
    sa.Column('simulation_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('anchor', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_annotations_simulation_id_simulations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_annotations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations'))
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_simulation_id'), ['simulation_id'], unique=False)

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('template_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.String(length=24), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('niche', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_simulations_niche'), ['niche'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_template_id'), ['template_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_simulations_reviewed_by_users'), 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_simulations_reviewed_by_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_simulations_template_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_score'))
        batch_op.drop_index(batch_op.f('ix_simulations_parent_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_niche'))
        batch_op.drop_column('niche')
        batch_op.drop_column('score')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_status')
        batch_op.drop_column('template_id')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_created_at'))

    op.drop_table('annotations')
    with op.batch_alter_table('audience_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audience_templates_shared'))
        batch_op.drop_index(batch_op.f('ix_audience_templates_org_id'))
        batch_op.drop_index(batch_op.f('ix_audience_templates_created_at'))

    op.drop_table('audience_templates')
    # ### end Alembic commands ###
