"""indexed signals cultural moments and archived context

Revision ID: 3491b37de7c7
Revises: 6fbee1b10c17
Create Date: 2026-10-03 20:26:57.553555
"""
import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision = '3491b37de7c7'
down_revision = '6fbee1b10c17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_bind().dialect.name == 'postgresql':
        op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultural_moments',
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('usage', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cultural_moments'))
    )
    with op.batch_alter_table('cultural_moments', schema=None) as batch_op:
        batch_op.create_index('uq_cultural_moment_region_day', ['region', 'day'], unique=True)

    op.create_table('signal_embeddings',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('vector', Vector(128).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_signal_embeddings_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_embeddings_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_embeddings'))
    )
    with op.batch_alter_table('signal_embeddings', schema=None) as batch_op:
        if op.get_bind().dialect.name == 'postgresql':
            batch_op.create_index('ix_signal_embeddings_cosine', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
        batch_op.create_index(batch_op.f('ix_signal_embeddings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_embeddings_signal_id'), ['signal_id'], unique=False)

    with op.batch_alter_table('region_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_key', sa.String(length=500), nullable=True))

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('simulation_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_signals_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_signals_org_id_organizations'), 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_signals_simulation_id_simulations'), 'simulations', ['simulation_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_signals_simulation_id_simulations'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_signals_org_id_organizations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_signals_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_signals_org_id'))
        batch_op.drop_column('simulation_id')
        batch_op.drop_column('org_id')

    with op.batch_alter_table('region_snapshots', schema=None) as batch_op:
        batch_op.drop_column('archive_key')

    with op.batch_alter_table('signal_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_embeddings_signal_id'))
        batch_op.drop_index(batch_op.f('ix_signal_embeddings_org_id'))
        if op.get_bind().dialect.name == 'postgresql':
            batch_op.drop_index('ix_signal_embeddings_cosine', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})

    op.drop_table('signal_embeddings')
    with op.batch_alter_table('cultural_moments', schema=None) as batch_op:
        batch_op.drop_index('uq_cultural_moment_region_day')

    op.drop_table('cultural_moments')
    # ### end Alembic commands ###
