"""Competitor monitoring (watches, alerts) and recurring re-runs.

Revision ID: 20261002_0003
Revises: 20261002_0002
Create Date: 2026-10-02 04:36:04.118724
"""
from alembic import op
import sqlalchemy as sa


revision = '20261002_0003'
down_revision = '20261002_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('feed_url', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('audience', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('seen', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_watches_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_watches_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_watches_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watches'))
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watches_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_last_checked_at'), ['last_checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_project_id'), ['project_id'], unique=False)

    op.create_table('alerts',
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('simulation_id', sa.String(length=32), nullable=True),
    sa.Column('watch_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_alerts_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], name=op.f('fk_alerts_simulation_id_simulations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], name=op.f('fk_alerts_watch_id_watches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_read'), ['read'], unique=False)

    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rerun_every_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('next_rerun_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_simulations_next_rerun_at'), ['next_rerun_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_next_rerun_at'))
        batch_op.drop_column('next_rerun_at')
        batch_op.drop_column('rerun_every_days')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_read'))
        batch_op.drop_index(batch_op.f('ix_alerts_org_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_project_id'))
        batch_op.drop_index(batch_op.f('ix_watches_org_id'))
        batch_op.drop_index(batch_op.f('ix_watches_last_checked_at'))
        batch_op.drop_index(batch_op.f('ix_watches_created_at'))
        batch_op.drop_index(batch_op.f('ix_watches_active'))

    op.drop_table('watches')
    # ### end Alembic commands ###
