"""Portal research checked 2026-10-04. Metadata only: no remembered statistics are seeded.

An adapter is not a reuse permission. Dataset-specific rights still need platform-admin approval.
Cadences describe intended imports; the imported observation always retains its native period.
"""
PULSE_TERMS = "https://www.dubaipulse.gov.ae/docs/DDE%20_%20DRAFT_Open_Data%20Licence_LONG_Form_English%203.pdf"
CONFIRM = "licence to confirm — public access alone does not establish commercial reuse rights"


def source(key, name, publisher, url, attributes, *, level="country", country="AE", method="report_pdf",
           cadence="irregular", terms="", licence=CONFIRM, notes="", config=None, status="pending_import"):
    return dict(key=key, name=name, publisher=publisher, country=country, geography_level=level, url=url,
        access_method=method, licence=licence, attribution=f"{publisher}; cite the dataset title, native period and original URL.",
        cadence=cadence, reliability=.5, notes=notes or "Download an aggregate table from this portal; import CSV/XLSX with its native geography, denominator and dates.",
        attributes=attributes, terms_url=terms or url, config=config or {}, status=status, licence_approved=False)


CATALOG = [
    source("fcsc_population", "FCSC UAE.Stat", "Federal Competitiveness and Statistics Centre", "https://uaestat.fcsc.gov.ae/en",
        ["population", "labour", "cpi", "household_expenditure", "trade"], method="api", cadence="annual",
        notes="Public SDMX population flow identified but returned HTTP 403 (Cloudflare) during verification. Download from UAE.Stat manually or request access; do not bypass the restriction. Map publisher code lists explicitly; other flows need separate mappings. Register-based figures retain their reference date, denominator and revision.",
        config={"adapter": "sdmx", "endpoint": "https://releaseeuaestat.fcsc.gov.ae/rest/data/FCSA,DF_POP_IND,2.7.0/....?format=csvfile"}),
    source("bayanat_ae", "Bayanat UAE open data", "UAE Government", "https://bayanat.ae/",
        ["population", "labour", "cpi", "household_expenditure", "trade"], method="file_download",
        notes="Download the publisher's specific resource, preserve its metadata and verify that its federal licence covers the selected file. The portal's general openness does not replace resource-level terms."),
    source("scad_statistics", "Abu Dhabi statistics", "Statistics Centre Abu Dhabi", "https://www.scad.gov.ae/",
        ["population", "labour", "cpi", "household_expenditure"], level="emirate", method="portal_registration",
        terms="https://www.scad.gov.ae/scad-policies",
        notes="Open-data policy promises machine-readable publication; microdata has separate restrictive conditions. Export aggregate population/labour tables and confirm the exact table's reuse terms."),
    source("dubai_statistics", "Dubai population and labour statistics", "Dubai Data and Statistics Establishment", "https://www.dsc.gov.ae/",
        ["population", "sex", "age", "labour", "cpi", "household_expenditure"], level="emirate", cadence="annual",
        terms="https://dsc.gov.ae/ar-ae/Pages/termsandcondition.aspx",
        notes="Website terms protect copyrighted content; an explicit commercial dataset licence has not been confirmed. Download population by age/sex and keep publication/reference dates."),
    source("dubai_pulse", "Dubai Pulse open datasets", "Digital Dubai", "https://www.dubaipulse.gov.ae/",
        ["population", "area", "housing", "commuting"], level="district", method="file_download", terms=PULSE_TERMS,
        licence="Published Dubai Open Data Licence permits commercial use with attribution and other conditions; licence to confirm for the selected resource.",
        notes="Choose a dataset and public CSV resource from the catalogue. Some APIs require registration. The published licence file is named DRAFT; confirm adoption and resource-specific rights before approval.", config={"adapter": "table"}),
    source("sharjah_statistics", "Sharjah census and statistics", "Department of Statistics and Community Development", "https://dscd.ae/",
        ["population", "nationality", "sex", "age"], level="emirate",
        notes="Request/export aggregate Sharjah census tables. Record census versus register methodology and reference period; no stable public machine-readable endpoint or commercial licence verified."),
    source("khda_schools", "Dubai private schools open data", "KHDA", "https://web.khda.gov.ae/en/Resources/KHDA-data-statistics",
        ["nationality_area_proxy", "income_area_proxy", "school_calendar"], level="district", method="file_download", cadence="annual",
        terms=PULSE_TERMS, config={"adapter": "table"},
        notes="Official page provides private-school open-data downloads. Import school/curriculum/fees/nationality/area only where actually present. School enrolment is a proxy, not resident nationality or household income; confirm file-specific licence."),
    source("adek_schools", "Abu Dhabi private schools", "ADEK", "https://www.adek.gov.ae/",
        ["nationality_area_proxy", "income_area_proxy", "school_calendar"], level="district", method="portal_registration",
        notes="Request aggregate school statistics and published school calendars. Public open-data page could not be verified; licence to confirm. Never treat pupil nationality as resident nationality."),
    source("dld_property", "Dubai sales and rents", "Dubai Land Department", "https://dubailand.gov.ae/en/open-data/real-estate-data/",
        ["income_area_proxy", "housing_type"], level="district", method="file_download", cadence="daily", terms=PULSE_TERMS, config={"adapter": "table"},
        notes="Download official sales/Ejari aggregate resources and verify their exact licence. Price/rent is a housing proxy; do not infer household incomes without an explicitly documented model."),
    source("rta_transport", "Dubai transport ridership", "Roads and Transport Authority", "https://www.dubaipulse.gov.ae/organisation/rta",
        ["commuting_proxy"], level="point", method="file_download", cadence="monthly", terms=PULSE_TERMS, config={"adapter": "table"},
        notes="Select a public station/line ridership file. Ridership is not a residence-to-work matrix: cross-emirate commute shares remain placeholders until such a table is imported."),
    source("det_visitors", "Dubai visitor performance", "Dubai Department of Economy and Tourism", "https://www.dubaidet.gov.ae/en/newsroom",
        ["visitor_source_country", "visitor_count"], level="emirate", cadence="monthly",
        notes="Download Tourism Performance/Annual Visitor reports. Visitors are flows with a native period, not resident stocks. Import source-country cells and their denominator separately."),
    source("cbuae_bulletins", "Central Bank statistical bulletins", "Central Bank of the UAE", "https://centralbank.ae/en/open-data-landing/",
        ["consumer_credit", "lending", "remittances"], cadence="monthly",
        terms="https://www.centralbank.ae/ar/open-data-landing/open-data-guidelines/",
        licence="Federal open-data terms and attribution are referenced; licence to confirm for selected bulletin and derived commercial use.",
        notes="Download native monthly/quarterly bulletin cells. Aggregate remittance totals do not establish an individual income remittance fraction."),
    source("doh_health", "Abu Dhabi health indicators", "Department of Health Abu Dhabi", "https://www.doh.gov.ae/en/resources/open-data",
        ["health", "insurance"], level="emirate", terms="https://www.doh.gov.ae/en/term-of-use",
        notes="Select public aggregate health indicators. General content terms require permission beyond allowed use; confirm the open-data dataset licence. No personal health data."),
    source("dha_health", "Dubai health statistics", "Dubai Health Authority", "https://www.dha.gov.ae/en/open-data",
        ["health", "insurance"], level="emirate", terms=PULSE_TERMS,
        notes="Import aggregate health/insurance tables; confirm the specific file's licence and covered resident denominator."),
    source("mohap_health", "Federal health open data", "Ministry of Health and Prevention", "https://mohap.gov.ae/en/web/guest/open-data/mohap-open-data",
        ["health", "insurance"], terms="https://mohap.gov.ae/documents/d/guest/open-data-policy-1",
        licence="MOHAP describes unrestricted use/distribution under UAE open-data policy; confirm the selected file's licence and exclusions.",
        notes="Download aggregate health reports/tables from the portal; retain geographical coverage and reference period."),
    source("tdra_digital", "Digital access and device indicators", "Telecommunications and Digital Government Regulatory Authority", "https://tdra.gov.ae/en/open-data.aspx",
        ["internet_access", "mobile_access", "devices"], terms="https://tdra.gov.ae/en/open-data/open-data-policy.aspx",
        licence="TDRA references UAE open-data specifications; licence to confirm for each resource.", cadence="annual"),
    source("glmm", "GLMM migration and nationality estimates", "Gulf Labour Markets, Migration and Population Programme", "https://gulfmigration.grc.net/",
        ["nationality", "migration"], notes="Import a cited UAE nationality estimate table with its original methodology/denominator. Estimates are not an official full nationality census. Commercial reuse terms not verified."),
    source("undesa_migrants", "UN DESA international migrant stock", "United Nations DESA Population Division", "https://www.un.org/development/desa/pd/content/international-migrant-stock",
        ["migrant_stock", "birth_country"], method="file_download", config={"adapter": "table"},
        notes="Download origin/destination Excel tables and metadata. Country of birth is not nationality; do not substitute it silently. Check UN data-use terms for this release."),
    source("india_mea", "India overseas population", "Ministry of External Affairs India", "https://www.mea.gov.in/population-of-overseas-indians.htm",
        ["indian_diaspora"], notes="Download the linked NRI/PIO table and record the source reference date. These totals do not provide Kerala/Hindi-belt shares; subgroups remain placeholders."),
    source("pakistan_beoe", "Pakistan overseas emigration statistics", "Bureau of Emigration and Overseas Employment Pakistan", "https://beoe.gov.pk/",
        ["pakistani_migration_flow"], cadence="monthly",
        notes="Download Reports & Statistics country/category tables. Registered deployments are flows, not the resident Pakistani population; do not substitute them for stocks."),
    source("philippines_dmw", "Philippines overseas worker statistics", "Department of Migrant Workers Philippines", "https://dmw.gov.ph/statistics",
        ["filipino_migration_flow"], notes="Portal returned a loading error during checking. Download official country/deployment tables when available; deployments are flows, not all Filipino residents. Licence to confirm."),
    source("arab_youth_survey", "Arab Youth Survey", "ASDA'A BCW / Arab Youth Survey", "https://arabyouthsurvey.com/",
        ["youth_attitudes", "media_habits"], cadence="annual",
        notes="Import only published UAE-specific Arab-youth cells and their sampling scope. No commercial reuse grant verified; does not represent UAE expats or older residents."),
    source("wvs", "World Values Survey", "World Values Survey Association", "https://www.worldvaluessurvey.org/WVSContents.jsp?CMSID=Documentation",
        ["attitudes"], method="portal_registration", terms="https://www.worldvaluessurvey.org/AJDownloadLicense.jsp",
        licence="Published download conditions restrict use to non-profit purposes and prohibit redistribution; commercial permission required.",
        notes="Check UAE inclusion in the exact wave before importing. Do not assume coverage. Separate written commercial permission is required; a general admin approval cannot replace that permission."),
    source("abu_dhabi_qol", "Abu Dhabi Quality of Life Survey", "Statistics Centre Abu Dhabi / Department of Community Development", "https://www.scad.gov.ae/",
        ["quality_of_life", "attitudes"], level="emirate", terms="https://www.scad.gov.ae/scad-policies",
        notes="Import published Abu Dhabi aggregate survey cells, with sample weights, population coverage and wave. Confirm data-request and reuse conditions."),
    source("global_findex", "World Bank Global Findex", "World Bank", "https://www.worldbank.org/en/publication/globalfindex",
        ["financial_access", "digital_payments"], method="api", terms="https://datacatalog.worldbank.org/public-licenses",
        licence="The FX.OWN.TOTL.ZS indicator page explicitly publishes CC BY 4.0; World Bank mandatory attribution terms also apply.",
        config={"adapter": "world_bank", "endpoint": "https://api.worldbank.org/v2/country/AE/indicator/FX.OWN.TOTL.ZS?format=json&per_page=1000", "metric": "financial_access", "unit": "percent"},
        notes="UAE indicator endpoint verified HTTP 200 on 2026-10-04. Adapter preserves survey-year cells and missing values. Denominator is population ages 15+, not all residents. Publisher metadata states triennial survey cadence (irregular in this registry's vocabulary)."),
    source("datareportal_ae", "DataReportal UAE digital reports", "DataReportal / Kepios", "https://datareportal.com/reports/?tag=United+Arab+Emirates",
        ["platform_habits", "social_users"], cadence="annual", terms="https://datareportal.com/citation",
        licence="Citation/republication policy permits limited fair-dealing reuse; full extraction and commercial model use need confirmation.",
        notes="Import a specifically cited table only after permission review. Ad reach, accounts and active users have different denominators; do not convert them into resident platform probabilities silently."),
    source("gcc_stat", "GCC-Stat MARSA data", "Statistical Centre for the Cooperation Council", "https://dp.marsa.gccstat.org/",
        ["regional_population", "labour", "cpi"], country="GCC", method="file_download", terms="https://www.gccstat.org/terms-of-use", config={"adapter": "table"}),
    source("sa_gastat", "Saudi GASTAT census and statistics", "General Authority for Statistics Saudi Arabia", "https://www.stats.gov.sa/",
        ["population", "labour", "cpi"], country="SA", terms="https://www.stats.gov.sa/en/microdata",
        notes="Register now for the later KSA rebuild. Download 2022 census, labour and CPI aggregate tables; verify specific open-data licence and distinguish census from current estimates."),
    source("placeholder_priors", "Kruvim placeholder model priors", "Kruvim", "https://github.com/leo777-debug/Kruvim/tree/kruvim/backend/app/services/population",
        ["all_unloaded_population_attributes", "salary_cycle", "synthetic_behavior"], method="manual", status="placeholder",
        licence="Synthetic model configuration, not measured statistics or official demographic data.",
        notes="Estimate, source pending. All unsupported numeric model priors and heuristic correlations trace here; these are explicitly not observations of real UAE people."),
]

# Public RSS availability and commercial reuse are separate. No article scraping adapters are provided.
NEWS = [
    ("gulf_news", "Gulf News", "https://gulfnews.com/", "https://gulfnews.com/about-gulf-news/term-conditions", "en", "", "Site terms limit use to personal/non-commercial use; written commercial permission required. No current publisher RSS endpoint verified."),
    ("khaleej_times", "Khaleej Times", "https://www.khaleejtimes.com/", "https://www.khaleejtimes.com/contact-us", "en", "", "No current publisher RSS endpoint or commercial reuse grant verified. Request an approved feed; do not scrape articles."),
    ("the_national", "The National", "https://www.thenationalnews.com/uae/rss-feeds-1.536712", "https://www.thenationalnews.com/uae/rss-feeds-1.536712", "en", "", "Publisher RSS page says personal use only and requires permission for commercial concerns. Confirm current feed with publisher."),
    ("wam", "Emirates News Agency WAM", "https://www.wam.ae/", "https://www.wam.ae/", "ar", "", "Current public RSS/API and commercial reuse grant not verified. Request permission or import licensed headline metadata manually."),
    ("al_khaleej", "Al Khaleej", "https://www.alkhaleej.ae/rss", "https://www.alkhaleej.ae/rss", "ar", "", "Publisher RSS directory verified. Select a linked UAE feed after confirming commercial reuse; copyrighted content is not automatically reusable."),
    ("al_bayan", "Al Bayan", "https://www.albayan.ae/", "https://www.albayan.ae/", "ar", "", "Public feed and current reuse terms need confirmation; no article scraping."),
    ("emarat_al_youm", "Emarat Al Youm", "https://www.emaratalyoum.com/rss-7.951867", "https://www.emaratalyoum.com/rss-7.951867", "ar", "", "RSS landing page verified; exact local-news XML endpoint and commercial permission still need confirmation."),
    ("gulf_today", "Gulf Today", "https://www.gulftoday.ae/rss", "https://www.gulftoday.ae/rss", "en", "https://www.gulftoday.ae/rssFeed/55/", "Publisher provides public News RSS; commercial reuse not expressly confirmed."),
]
for key, name, url, terms, lang, feed, notes in NEWS:
    CATALOG.append(source(key, name, name, url, ["regional_headlines", "news_tone"], level="emirate", method="api" if feed else "manual",
        cadence="daily", terms=terms, notes=notes, config={"adapter": "rss", "feed_url": feed, "lang": lang} if feed else {}))
